local ui = gpuix

local colors = {
    canvas = "#15171c",
    sidebar = "#111318",
    raised = "#1d2027",
    hover = "#252933",
    border = "#2d323d",
    text = "#e5e7eb",
    muted = "#9ca3af",
    faint = "#6b7280",
    accent = "#e2795b",
    blue = "#60a5fa",
    green = "#34d399",
}

local styles = {
    root = ui.style {
        width = "100%",
        height = "100%",
        display = "flex",
        flexDirection = "row",
        background = colors.canvas,
        color = colors.text,
    },
    sidebar = ui.style {
        width = 248,
        height = "100%",
        display = "flex",
        flexDirection = "column",
        padding = 14,
        gap = 10,
        background = colors.sidebar,
        borderRightWidth = 1,
        borderColor = colors.border,
    },
    sidebar_compact = ui.style {
        width = 88,
        height = "100%",
        display = "flex",
        flexDirection = "column",
        padding = 10,
        gap = 10,
        background = colors.sidebar,
        borderRightWidth = 1,
        borderColor = colors.border,
    },
    content = ui.style {
        display = "flex",
        flexDirection = "column",
        flexGrow = 1,
        minWidth = 0,
        height = "100%",
    },
    header = ui.style {
        height = 58,
        display = "flex",
        flexDirection = "row",
        alignItems = "center",
        paddingLeft = 18,
        paddingRight = 18,
        gap = 10,
        borderBottomWidth = 1,
        borderColor = colors.border,
    },
    body = ui.style {
        display = "flex",
        flexDirection = "row",
        flexGrow = 1,
        minHeight = 0,
    },
    detail = ui.style {
        display = "flex",
        flexDirection = "column",
        flexGrow = 1,
        minWidth = 0,
        padding = 20,
        gap = 14,
        overflow = "scroll",
    },
    activity = ui.style {
        width = 360,
        flexShrink = 0,
        display = "flex",
        flexDirection = "column",
        padding = 14,
        gap = 8,
        borderLeftWidth = 1,
        borderColor = colors.border,
        background = colors.sidebar,
        overflow = "scroll",
    },
    card = ui.style {
        display = "flex",
        flexDirection = "column",
        padding = 14,
        gap = 8,
        borderRadius = 10,
        background = colors.raised,
        borderWidth = 1,
        borderColor = colors.border,
    },
    button = ui.style {
        display = "flex",
        flexDirection = "row",
        alignItems = "center",
        paddingLeft = 11,
        paddingRight = 11,
        paddingTop = 7,
        paddingBottom = 7,
        borderRadius = 7,
        background = colors.raised,
    },
    button_active = ui.style {
        display = "flex",
        flexDirection = "row",
        alignItems = "center",
        paddingLeft = 11,
        paddingRight = 11,
        paddingTop = 7,
        paddingBottom = 7,
        borderRadius = 7,
        background = colors.accent,
        color = "#17181c",
    },
    composer = ui.style {
        display = "flex",
        flexDirection = "row",
        alignItems = "center",
        padding = 12,
        gap = 10,
        borderTopWidth = 1,
        borderColor = colors.border,
    },
    input = ui.style {
        flexGrow = 1,
        minWidth = 0,
        padding = 10,
        borderRadius = 8,
        background = colors.raised,
        color = colors.text,
    },
}

local native_theme = {
    text = colors.text,
    textMuted = colors.muted,
    border = colors.border,
    bg = colors.canvas,
    accent = colors.accent,
    codeText = "#f0ab82",
    codeWash = "#ffffff0d",
}

return {
    colors = colors,
    styles = styles,
    native = native_theme,
}
